
#Common settings
[common]
	#Automatically generate vertical slabs
	automatic_slabs = true
	#Automatically generate vertical stairs
	automatic_stairs = true
	#Automatically generate wall and ceiling carpets
	automatic_carpets = true
	#Automatically generate wall and ceiling pressure plates
	automatic_pressure_plates = true
	#Automatically generate wall and ceiling weighted pressure plates
	automatic_weighted_pressure_plates = true
	#Disable automatic vertical slab placement. Use if a mod E.G. DoubleSlabs is conflicting.
	disable_slab_placement = false
	#Disable automatic vertical stair placement. Use if a mod is conflicting.
	disable_stair_placement = false
	#Disable automatic wall and ceiling carpet placement. Use if a mod is conflicting.
	disable_carpet_placement = false
	#Disable automatic wall and ceiling pressure plate placement. Use if a mod is conflicting.
	disable_pressure_plate_placement = false
	#Disable automatic wall and ceiling weighted pressure plate placement. Use if a mod is conflicting.
	disable_weighted_pressure_plate_placement = false
	#Show tooltip when a block has additional placements
	tooltip = true
	#Blacklist for blocks to not have generated placement variants
	blacklist = []
	#Blacklist for mods to not have generated placement variants
	mod_blacklist = []
	#Whitelist for blocks from blacklisted mods to still have generated placement variants
	mod_block_whitelist = []

