
#General settings
[general]
	#Use config instead of datapack
	use_config = true

	#List settings
	#Syntax: ["modid:block|weight"]
	#Example: ["minecraft:stone|2","minecraft:dirt|1"]
	#Forge tags are supported
	[general.lists]
		#Cobble gen
		block_list_cobble = ["tfc:rock/hardened/rhyolite|1"]
		#Stone gen
		block_list_stone = ["tfc:rock/hardened/granite|1"]
		#Basalt gen
		block_list_basalt = ["minecraft:basalt|60", "minecraft:blackstone|60", "minecraft:netherrack|60", "minecraft:nether_quartz_ore|30", "minecraft:nether_gold_ore|30", "minecraft:ancient_debris|1"]

		#Custom settings
		[general.lists.custom]
			#Custom generators
			#Syntax: [gen]
			#Gen: [type, block, list]
			#Type: cobblestone, stone
			#Block: resource location of the block below the generated block
			#List: see List settings
			#Examples:
			#custom_generators = [
			#   ["cobblestone", "minecraft:diamond_block", ["minecraft:diamond_block"]],
			#   ["cobblestone", "minecraft:dirt", ["forge:dirt"]],
			#   ["cobblestone", "minecraft:white_wool", ["minecraft:wool"]]]
			custom_generators = [["cobblestone", "tfc:rock/gravel/rhyolite", ["tfc:rock/hardened/rhyolite|1"]], ["cobblestone", "tfc:rock/gravel/basalt", ["tfc:rock/hardened/basalt|1"]], ["cobblestone", "tfc:rock/gravel/andesite", ["tfc:rock/hardened/andesite|1"]], ["cobblestone", "tfc:rock/gravel/dacite", ["tfc:rock/hardened/dacite|1"]], ["stone", "tfc:rock/gravel/rhyolite", ["tfc:rock/hardened/rhyolite|1"]], ["stone", "tfc:rock/gravel/basalt", ["tfc:rock/hardened/basalt|1"]], ["stone", "tfc:rock/gravel/andesite", ["tfc:rock/hardened/andesite|1"]], ["stone", "tfc:rock/gravel/dacite", ["tfc:rock/hardened/dacite|1"]], ["cobblestone", "tfc:rock/gravel/granite", ["tfc:rock/hardened/granite|1"]], ["cobblestone", "tfc:rock/gravel/diorite", ["tfc:rock/hardened/diorite|1"]], ["cobblestone", "tfc:rock/gravel/gabbro", ["tfc:rock/hardened/gabbro|1"]], ["stone", "tfc:rock/gravel/granite", ["tfc:rock/hardened/granite|1"]], ["stone", "tfc:rock/gravel/diorite", ["tfc:rock/hardened/diorite|1"]], ["stone", "tfc:rock/gravel/gabbro", ["tfc:rock/hardened/gabbro|1"]]]

