#Should you be able to equip from inventory?
canEquipFromInventory = false
#Should items you pick up be automatically added to your backpack?
autoAddToBag = false
#Can you add stuff to your backpack like you would a Bundle?
bundleAdd = false
#Should the tooltip display the inventory?
inventoryToolTip = false
#How much armor does the backpack provide?
#Range: 1 ~ 20
backpackDefenseLevel = 2
#How likely is it that a mob will drop a backpack?
#Range: 0 ~ 100
entityBackpackChance = 10
#How much durability does the backpack have?
#Range: 1 ~ 9999
backpackDurability = 80
#Can you use a keybind to open an equipped Backpack?
canOpenWhileEquipped = false
#Can you enchant your backpack?
canEnchantBackpack = true
#Can you open your backpack with your hand?
canOpenWithHand = false
#Can you open other people's backpacks?
canOpenOthers = false
#How many rows does your backpack have?
#Range: 1 ~ 13
rows = 4
#How many columns does your backpack have?
#Range: 1 ~ 20
columns = 9

