onEvent('recipes', event => {
    event.remove({id: 'create:compacting/chocolate'})
    event.remove({id: 'farmersdelight:cooking/cooked_rice'})
    event.remove({output: 'farmersdelight:fried_egg'})
    event.remove({id: 'farmersdelight:cutting/cabbage'})
    event.remove({id: 'farmersdelight:integration/create/mixing/cabbage_slice_from_mixing'})
    event.remove({id: 'farmersdelight:cabbage_from_leaves'})
    event.remove({input: 'farmersdelight:rice_panicle'})
    event.remove({output: 'farmersdelight:rice'})
    event.remove({input: 'farmersdelight:milk_bottle'})
    event.remove({output: 'farmersdelight:milk_bottle'})
    event.remove({output: 'firmalife:food/pickled_egg'})

    event.remove({id: 'firmalife:mixing_bowl/pizza_dough'})
    event.remove({id: 'firmalife:pot/tomato_sauce'})
    event.remove({id: 'firmalife:vat/tomato_sauce'})
    event.remove({output: 'firmalife:crafting/tomato_sauce_mix'})
    event.remove({output: 'farmersdelight:melon_popsicle'})
})